# Generated by Django 2.2.8 on 2019-12-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('icon', models.ImageField(upload_to='icon/')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('translation', models.CharField(max_length=64)),
                ('transcription', models.CharField(max_length=64)),
                ('example', models.TextField()),
                ('sound', models.FileField(upload_to='sound/')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Theme')),
            ],
        ),
    ]
